### ISSUE TITLE
Asset cleaner failures

### ISSUE THREAD

**Issue by RSulzmann** [apache/openwhisk#1856]
In a unit testcase, intermittent failures occur when cleaning up a package containing an action.
error: Package delete failed: Package not empty (contains 1 entity) (code 2972066)
exit code: 153 was not equal to 0

exception :
org.scalatest.exceptions.TestFailedException: deletedAll was false some assets were not deleted
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
	at org.scalatest.FlatSpec.newAssertionFailedException(FlatSpec.scala:1683)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
	at common.WskTestHelpers$class.withAssetCleaner(WskTestHelpers.scala:105)
	at system.basic.WskBasicTests.withAssetCleaner(WskBasicTests.scala:38)
	at system.basic.WskBasicTests$$anonfun$7.apply$mcV$sp(WskBasicTests.scala:115)

In the file WskTestHelpers.scala the function withAssetCleaner should also include a retry ...

```           // delete assets in reverse order so that was created last is deleted first
            val deletedAll = assetsToDeleteAfterTest.reverse map {
                case ((cli, n, delete)) => n -> Try {
                    if (delete) {
                        cli.delete(n)(wskprops)
                    } else {
                        cli.sanitize(n)(wskprops)
                    }
                }
```

similar like in class AssetCleaner :

```  // retry sanitization on a package since there may be a list (view)
                            // operation that requires a retry for eventual consistency
                            whisk.utils.retry({
                                cli.sanitize(name)(wskprops)
                            }, 5, Some(1 second))
```

**Comment by rabbah** [comment]
going to close https://github.com/openwhisk/openwhisk/issues/1588 as duplicate.

**Comment by rabbah** [comment]
Fixed with https://github.com/openwhisk/openwhisk/pull/1943.

**Comment by eweiter** [comment]
This issue appears to be happening again. 
Earlier today the YPHealth build failed multiple times (not successively) due to seemingly this error, where it tried to delete a package but the package deletion failed because it still contained an action within it. 

The last failure was in the test
"system.basic.WskConsoleTests.Wsk Activation Console should show an activation log message for hello world"
where it failed due to:
`
ERROR: deleting asset failed for samples: org.scalatest.exceptions.TestFailedException: /home/jenkins/.local/bin/wsk -i --apihost bluemix.net --apiversion v1 package delete --auth ... /_/samples error: Unable to delete package 'samples': Package not empty (contains 1 entity) (code 350922) exit code: 153 was not equal to 0
`

A couple builds before the above failure the test
"system.basic.WskPackageTests.Wsk Package should perform package binds so parameters are inherited"
failed due to: 
`
Starting test Wsk Package should perform package binds so parameters are inherited at 2017-04-21 16:27:03.146
ERROR: deleting asset failed for package1: org.scalatest.exceptions.TestFailedException: /home/jenkins/.local/bin/wsk -i --apihost bluemix.net --apiversion v1 package delete --auth ... /_/package1
error: Unable to delete package 'package1': Package not empty (contains 1 entity) (code 324970)
exit code: 153 was not equal to 0
`
