### ISSUE TITLE
selenium-in-whisk requires an increase in pids-limit and MAX_MEMORY

### ISSUE THREAD

**Issue by starpit** [apache/openwhisk#1951]
to run selenium (with geckodriver) in whisk, at least 128 processes and 700MB of memory are required. this is for simple pages; for more complex pages, i expect memory requirements to go up.

the current hard limits are 64 processes and 512MB memory per invocation.

**Comment by csantanapr** [comment]
I remember someone proposing to increase to 256

**Comment by perryibm** [comment]
Consistent with our scaling story, we can tie pid-limit to memory size since they likely go together.  The bigger decision, IMO, is the addition of a 1GB size.

**Comment by sjfink** [comment]
@perryibm : true or false:  if we make the container pool memory size aware, we could/should support any reasonable memory size.   

That is, perhaps we should "do the right thing" and support, say, any multiple of 128 MB up to 2GB.

**Comment by perryibm** [comment]
I think having many multiples of 128MB is fine and would be a good thing when we support memory sizes better in the load balancer/invoker.  I suppose the question is whether we add a 1GB (or 768MB) in the short term.

**Comment by sjfink** [comment]
in the future, do we think we'll have different flavors of invokers?   i.e. segregate "big memory" jobs onto a subset of the invokers?

Seems like it might be a reasonable long-term strategy for managing the bin packing globally and avoid fragmentation ("large object space" anyone?  JikesRVM joke)  
.... but haven't thought it through deeply.

**Comment by perryibm** [comment]
That sort of bin packing works well if there aren't too many sizes because the typical wastage is proportional to the number of sizes you support.   Every multiple of 128MB up to 2GB would be 16 sizes so up to 16 VMs could get wasted in the sense that there could be a VM running just a single 1920MB and other jobs cannot make it there.   The other issue with segregating is that you need to rebalance and dynamically update the invoker flavor and of course this means scheduling to shrink the number of machines as the system detects that a particular size is becoming overprovisioned.  Because of these effects, there is a desire to limit the number of sizes somewhat, a typical sizing (a la free lists) would often be something a little graduated like 128, 256, 384, 512, 768, 1024, 1.25, 1.5, 1.75, 2.

**Comment by sjfink** [comment]
so I wasn't thinking segregated lists for each size -- maybe 2 lists to start ... "up to 256MB" and "up to 2GB"

**Comment by rabbah** [comment]
There are production deployments of openwhisk with large memory support already.
