### ISSUE TITLE
cannot update or delete actions with missing attachments

### ISSUE THREAD

**Issue by jberstler** [apache/openwhisk#2051]
In the case that an action is missing its attachment, it cannot be updated or deleted. Updating results in a "concurrent modification" error from the CLI, and deleting has an error claiming that the resource doesn't exist.

The underlying cause of the problem is that `WhiskAction.get` attempts to fetch the attachment for the action and, upon failing to find it, then declares that the action itself does not exist.

Actions with missing attachments (however they happen) should be tolerated at least in that they can be updated and deleted.

**Comment by koelschkellerkind** [comment]
I have the same issue. Is there already any solution for this?

**Comment by rabbah** [comment]
😓 sorry you ran into this old issue - a workaround is to delete the document directly from couchdb (`wskadmin db delete`).

**Comment by koelschkellerkind** [comment]
Thank you for your fast reply! 

I could also solve the problem via the UI from CouchDB. You can access it via `http://OW_HOST_ADDRESS:32174/_utils/`.  In the database `test_whisks` you can then remove the respective functions.

**Comment by bdoyle0182** [comment]
@rabbah I'd like to try to solve this issue. Or at least do conflict resolving from the couchdb provider since the real root issue is not having conflict resolution of couchdb within the controller. Do you have any more info we could sync on for me to attempt to debug, we see it frequently enough for users where for whatever reason the attachment is missing and then the document is in a corrupted state which requires sys admins to ameliorate? Any idea on how docs are getting uploaded without attachments?

**Comment by bdoyle0182** [comment]
closing should be fixed on master
