### ISSUE TITLE
Feature request: Make logs available via docker logs command

### ISSUE THREAD

**Issue by style95** [apache/openwhisk#2057]
Currently, user can get logs by `wskadmin syslog` or accessing `/tmp/wsklogs/`

However, getting the container logs using `docker logs` command is more natural and common in docker echo-system.

If container writes logs to stdout too, it will be available via `docker logs`

It will be the best that not only core components logs but also action container logs are available.

**Comment by domdom82** [comment]
@perryibm ^^

**Comment by markusthoemmes** [comment]
FWIW: action container logs are available via `docker logs` already.

**Comment by domdom82** [comment]
regarding action logs we have hit a performance issue in the past. need to verify if it still exists but I assume it does. `docker logs` is relatively expensive which is why we are not using it to fetch action container logs in the invoker. as a user you can fetch them already. 

core containers are a bit trickier because we need them also in a file because we want to be able to forward them to log processing systems. need to check if both json-docker logs and file logs are possible.

**Comment by style95** [comment]
@domdom82 regarding performance issue, you meant if user try to get logs while action container is running, it will degrade the performance of system?

**Comment by markusthoemmes** [comment]
For core containers we can just use `tee` to pipe to the file + have it printed on stdout.

**Comment by style95** [comment]
I am not sure about log processing systems.
Docker daemon saves logs to file even though container writes logs to stdout, even though the location is little bit tricky.

**Comment by rabbah** [comment]
The logs from the components go to stdout but the docker run pipes that to a file. It's not a tee. The file is mounted in the host where it can be forwarded to elk for example. 

Use "wskadmin syslog get" to dump all logs for controller and invoker0 or "wskadmin syslog get controller" for just controller etc.

**Comment by markusthoemmes** [comment]
@rabbah we could use tee though, to have both the file and stdout (`docker logs`)

**Comment by rabbah** [comment]
To see the component logs, as markus suggested, we can add a tweak to the docker file I suppose. Not sure it's that useful, is it?

Do you want just to get logs? Or tail -f the logs? We can add that to wskadmin in which case, what does docker logs get you?

Are you thinking about a drain adapter or for local development?

**Comment by style95** [comment]
Regarding the idea to send the logs to stdout as well as file, docker daemon stores the logs to files also, there will be duplicate information.

For example, docker daemon stores logs in `LogPath` which is retrieved by `docker inspect`.
Normally that is the container directory in `/var/lib/docker/`

So if we send logs to file and stdout using tools like tee, there will be duplicate information stored in host file system. 

And with regard to this feature request, when I first met OW, I have no idea on `wksadmin` and `/tmp/wsklogs`.
So I just tried `docker logs` to see the logs and no shot.
And I got into the container using `docker exec -it bash` and saw the logs.

There is no specific requirement or thinking.
I just thought that many people who are not yet familiar with OW but familiar with docker, may think like the way I did, and if OW supports this feature, it will make them see the logs more easily.

**Comment by rabbah** [comment]
Fair points. Since in openwhisk we have not included the forwarded, we could send the logs to stdout instead so that as you someone starts developing its familiar to them. And then treat the file redirect and wskadmin as advanced features because really they're more handy than docker logs. 

Or we can better document how-tos for developers. Maybe an FAQ?
