### ISSUE TITLE
Fail to connect with Netezza database when using virtualenv to include the python package

### ISSUE THREAD

**Issue by bigmianhua** [apache/openwhisk#2373]
## Environment details:

Mac OS: 10.12.3 , docker version: 17.03.1-ce-mac5, python3, virtualenv
## Steps to reproduce the issue:

1.   Including jaydebeapi, Jpype packages and jar-file of driver required for connecting netezza database in virtualenv site package
2.   Uploading the zip file as a python3 action

## Provide the expected results and outputs:

```
Connect to Netezza database successfully

```

## Provide the actual results and outputs:

```
Fail to compile the included packages
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by jeremiaswerner** [comment]
@bigmianhua have you tried the following procedure by building the .zip in the target environment rather than on the client environment?
https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#packaging-python-actions-with-a-virtual-environment-in-zip-files

especially using this command:
```
docker run --rm -v "$PWD:/tmp" openwhisk/python3action sh \
  -c "cd tmp; virtualenv virtualenv; source virtualenv/bin/activate; pip install -r requirements.txt;"
```
