### ISSUE TITLE
Discussion: Should the catalog repository use a pinned version?

### ISSUE THREAD

**Issue by jberstler** [apache/openwhisk#2473]
https://github.com/apache/incubator-openwhisk/blob/master/ansible/group_vars/all#L257

When installing the catalog, the HEAD of the master branch is currently always pulled. While we take care to only merge stable changes, mistakes can happen and bugs could be introduced. Instead of always pulling from HEAD, we could pin this value to a specific tag or commit hash, which requires a separate update (presumably after integration testing is done) to pull in new versions.

Thoughts? @jasonpet @akrabat @rabbah

**Comment by rabbah** [comment]
I think the catalog should be installed like the alarm, cloudant, and Kafka feeds: from their own repos. I don't install the catalog from this repo because for day to day developelent it's not needed. And when I do need to, I don't run post deploy/catalog playbook and instead run out of the catalg repo (which then allows for controlled deployment like you're suggesting). 

I would package a post deploy playbook perhaps in an extras repository, and do the pinning there. My hestiation to pinning the catalog from this repo is we end up with lots of "bump" commits. 

In general we are striving to have as few circular dependencies in this repo to dependent repos. So I would severe dependence on the catalog. With the exception of the swift tests, I think all tests in this repo are self contained.

**Comment by akrabat** [comment]
I'm generally in favour of separation wherever possible.
