### ISSUE TITLE
Truncate Entity Names from CLI List Commands

### ISSUE THREAD

**Issue by dubee** [apache/openwhisk#2484]
Output returned from a CLI list command is not guaranteed to be formatted properly as entity names are not truncated.

Ex

```
$ wsk package list
packages
/namespace/9992                                           private
/namespace/aaaaaaa                                        private
/namespace/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa private
/namespace/asdfasdfasdfasedf2                             private
```

**Comment by jessealva** [comment]
any idea how we want to truncate?  Its super easy to just do something like chopping off all the characters after some size N.  What I've seen to be pretty popular is to have something like "myreallylongteststringtotruncate" be turned into something like "myreallylong...ncate". 

Since our current padding max length for package name is 70 characters, we can reserve say, 67 for the name (to give a 3 space padding between the end of the name and the start of the publish state field) and then break up the same such that we do something like always printing the first 54 characters, 3 periods, and then the last 10 characters of the string.
