### ISSUE TITLE
OpenWhisk with another database like Cassandra or Redis?

### ISSUE THREAD

**Issue by spattewar** [apache/openwhisk#2849]
Can you use Cassandra or Redis instead of CouchDB for all the functionalities? If yes does anyway has steps or method to do it? I have successfully installed openwhisk locally on ubuntu 14.0 and want to use another database as the backend.

Appreciate your time and help.

Thanks and Regards.

**Comment by rabbah** [comment]
I’m not aware of anyone having tried this yet. In principle the artifact store interface could be adapted to other data stores. In practice we’ve gone down a fair bit the couch db api. It may require some refactoring and maybe some rearchitecting.

**Comment by devbv** [comment]
I changed ArtifactStore from Couchdb to Mongodb in my project. I had not only to write new SPI module of ArtifactStore, but also to rewrite WhiskEntityQueries and some other codes. I'd tried to do it clearly, but it slightly ruined codebase. Because current openwhisk architecture is not suitable for any other database. You might need some understanding of openwhisk architecture and context of all queries for doing it.

**Comment by chetanmeh** [comment]
@devbv We are also looking into Mongodb support. Would it be possible for you to share the fork?

**Comment by spattewar** [comment]
Thanks @rabbah , @devbv , @chetanmeh for your comments. Sorry for the delay in my response as i just picked this up again.

One more option to changing the artifact would be to write an action that writes to another database. I think couchdb is only used to store action, default parameters, sequences, users, credentials etc. Am i  correct?

thanks again for your time.
Regards

**Comment by rabbah** [comment]
The store implementation is pluggable. We welcome other implementations.
