### ISSUE TITLE
The command list of activations does not work correctly for the first time when issued, but works fine the second time.

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk#2907]
I came across this issue recently when I am rewriting Rest interface for the test cases. 
The environment is local openwhisk deployment.
The list operation of activations does not work for the first time, if there are changes to the activations. However, it works for the second time.

For example, we create an action and invoke it. An activation ID is received. Even if this activation has assigned an ending time, which means it has been completed and we can get the activation's information by "wsk activation get <activation id>", we will not get this activation listed by "wsk activation list". However, if we run the command "wsk activation list" for the second time, the activation will show up.

I am sure this is an issue with the server, not the client, because I tried both the cli command and the rest call. It turned out the same result.

**Comment by rabbah** [comment]
This is not a bug. The queries were allowed to return stale results some time ago. The reason the second works is that a view update gets scheduled after the first and you get the result on the second list.

**Comment by rabbah** [comment]
In essence for tests using list you need a retry.

**Comment by markusthoemmes** [comment]
That's CouchDB behavior, we'd need to configure it in a way, that it computes views asynchronously in the background without getting any requests to that view.

**Comment by mluds** [comment]
Can this be reopened? The behavior is really unintuitive. The only reason I run this command is to see the latest activations so I can see the output, but it requires running it twice, and there's no mention of this in the --help message.

**Comment by rabbah** [comment]
@mluds it's better as a new issue and a note to the `dev` list.

Are you deploying your own openwhisk instance? The behavior cannot be changed through a csonfiguration parameter but cannot be changed system wide. See this `StaleParameter` object.
https://github.com/apache/openwhisk/blob/be1e3a19c02956c9be85023a0bb0ff399c21444d/common/scala/src/main/scala/org/apache/openwhisk/core/database/ArtifactStore.scala#L34-L38

The default is configured to allow the index to be updated after a request is made which is why the second request often works.
