### ISSUE TITLE
Control Container Capabilities?

### ISSUE THREAD

**Issue by joshuabuildsthings** [apache/openwhisk#3454]
## This is a feature request, not a bug report.

It looks like the OpenWhisk Invoker automatically drops the Net Admin Capability for all Action containers. Is it possible to keep this capability on a per Action basis?

[Invoker with --cap-drop](https://github.com/apache/incubator-openwhisk/blob/master/core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala)

If not, is it possible to add functionality to configure the capabilities on a per Action basis?

I want this because I have a use case where using tools like tc to throttle bandwidth would be useful. As these are lightweight & periodic tasks, I think FaaS/Serverless via OpenWhisk is the right way to go.

## Expected Results
To be able to configure capabilities of container when configuring the Action.

## Actual Results
NET_RAW & NET_ADMIN are explicitly stripped by the Invoker. There appears to be no way to configure capabilities.

**Comment by rabbah** [comment]
It's easier to make this a deployment time parameter for the system vs per action. Did you mean per action?

**Comment by joshuabuildsthings** [comment]
@rabbah - Please bear with me, I'd like to clarify terminology & make sure I'm using it correctly!

I'm currently assuming that what you're saying is that it would be easier to add this feature so it's system-wide & affects all actions equally?

**Comment by rabbah** [comment]
> I'm currently assuming that what you're saying is that it would be easier to add this feature so it's system-wide & affects all actions equally?

correct.

**Comment by rabbah** [comment]
> I'm guessing it may have inspired the --cap-drop in the Invoker.

I'll defer to @jeremiaswerner and @markusthoemmes on the details but in general yes.

Another relevant question: Are you using kubernetes to deploy opnewhisk?

**Comment by joshuabuildsthings** [comment]
Yes. Currently evaluating it for my use case on a local minikube setup.

**Comment by rabbah** [comment]
cc @dgrove-oss

**Comment by tysonnorris** [comment]
You could pretty easily change these from hard coded to system-wide configurations by setting them as default values on the `whisk.container-factory.container-args.extra-args` config:
https://github.com/apache/incubator-openwhisk/blob/d7c9fd661a8a5b339f20b3f549bfa4fa47124706/core/invoker/src/main/resources/application.conf#L55
(and deleting the hard coded bits in InvokerReactive)


To do this per action may be weird though, since generally you will want to maintain some restrictions over args passed to `docker run`, I think. 

To keep that control, but make it accessible, you might be able to add something like `extra-args` that are based on image name, so that you (as OW operator) can allow only some specific images to be launched with a different set of args.

**Comment by thomasknauth** [comment]
Piggy-backing on this thread: What is the exact syntax to use in this case? I want to pass --device=/dev/mydev to docker run. How would that be encoded in extra-args? Thanks!

**Comment by thomasknauth** [comment]
Figured it out myself: extra-args: { "device": ["/dev/mydev"] }
