### ISSUE TITLE
Ansible playbook apigateway.yml stuck at waiting for redis

### ISSUE THREAD

**Issue by Pyons** [apache/openwhisk#3481]
## Environment details:

* native ubuntu 
* version:
   * docker: 17.12.1-ce
   * ubuntu: 17.10

## Steps to reproduce the issue:
```
ansible-playbook couchdb.yml
ansible-playbook -i environments/local initdb.yml
ansible-playbook -i environments/local wipe.yml
ansible-playbook -i environments/local apigateway.yml
``` 

## Provide the expected results and outputs:

```
Ansible playbook should finish
```

## Provide the actual results and outputs:
Stuck at this point:
```
TASK [redis : wait until redis is up and running] ***********
```
Even though ``` docker ps ``` reports redis as running

**Comment by m4dj4ck** [comment]
nc command kept the connection upon successful connection to port 6379, thus unable to register to result. My workaround is to add '-q 2' parameters to nc, in so that nc will close the connection in 2 seconds. Like this :

`
action: shell (echo PING; sleep 1) | nc -q 2 {{ ansible_host }} {{ redis.port }}`
