### ISSUE TITLE
Rules with multiple triggers

### ISSUE THREAD

**Issue by ioana-blue** [apache/openwhisk#405]
Talking to potential users, someone expressed interest in a special type of rule that has one action which is invoked upon receiving a collection of triggers (i.e., only after _all_ triggers are fired). 

Not sure whether we already have an issue to cover such a feature.

**Comment by csantanapr** [comment]
I don't think is practical since a feed keeps sending events and firing triggers for the same feed, knowing that all are trigger is hard to define without saving state.

For example take web page, imaging that you want to  run a single action only with a set of events fire.

For example Q key is press, A key press and Z key press

Now start pressing all 3 keys like crazy :-)

The events will not be fire at the same time, and will be multiple of each.

Now do you want to run the action when? 

The first time Q, A, Z are press no matter the order? 

I think user can implement today with current low level construct we have, by saving state/storage like a counter, increase until reach 3, then reset to 0 & fire a trigger for action to run.
one action will be in charge of increasing the counter and firing the trigger for the final rule that wants to run the action only when the 3 events have occurred

maybe I'm wrong and don't understand the use case.

**Comment by ioana-blue** [comment]
I agree it can be implemented with our current API, but I think it will have some overhead. So the real question is whether there are enough use cases like this one to justify us dealing with managing the state of the triggers instead of the user of our system.

**Comment by mbehrendt** [comment]
i think this is a potentially interesting future item, but don't see it as a short-term item -- the implementation can become very complex, and would therefore prefer to first harden more basic scenarios.

**Comment by rabbah** [comment]
You can do this with the composer now.
