### ISSUE TITLE
How to specify -v parameter for docker containers that run functions?

### ISSUE THREAD

**Issue by YangZhou1997** [apache/openwhisk#4460]
HI all, 

I am trying to implement a shared memory between the running functions and the outside host. I planned to use the -v (volumes) feature of docker to share files between docker containers and the outside. Particularly, the -v parameter for docker container requires to be set during the container invoking phase. 

However, I did not find any API in openwhisk that I can use to set the -v parameter for containers that run functions, during the container invoking phase. If currently there is no such API provided, can anyone point out which source file might be a good starting point to hack on (to implement the functionality of specifying the -v parameter)? 

Any suggestions are highly appreciated!

**Comment by YangZhou1997** [comment]
I think I find a workable way to specify any parameter for docker run xxx -- changing this line of code: https://github.com/apache/incubator-openwhisk/blob/5a2bf810dc5fda2f0d184c022e5931ac65de9721/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerClient.scala#L135

Just wondering if there is a more elegant way to do so.

**Comment by style95** [comment]
@YangZhou1997 
What kinds of scenario do you keep in your mind?
IMHO, it is not that simple to provide volume mapping features in OpenWhisk.

Currently, it is not guaranteed for actions to run on the same invoker, it's not easy to mount the same directory on each call. Even if a container runs with volume mapping, it will be paused after 50ms.
Since we can add volume at container creation time, it will induce a bigger ColdStart time.
And if you are thinking of a shared volume at the host level, you need to take care of a concurrent modification issue. Also, one user's volume should not be accessed by the others, you need proper permission and multi-tenancy support as well. I think there might be more issues than I described.
So it is generally recommended to use object storages for serverless.

If you still want to try the way, I think `DockerClient` would be a good starting point.
Since users should be able to configure their volume, one option could be relying on annotations.
So users would specify volume information in annotation and OpenWhisk adds volume mapping based on the information at container creation time. 

Since I pondered on this shortly and naively, please consider that there would be some issues.

And you may find this useful for this kind of discussion.
https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md#discussion

We have slack channels and dev mailing list.

**Comment by YangZhou1997** [comment]
@style95 Thanks for the comments! 

The scenario in my mind is: can we have an openwhisk with direct message passing among serverless functions, instead of relying on a global long-running object store for message passing. Then I turn to the opensourced openwhisk platform to see if I could add the direct message passing to it. That is why I was seeking how to set the -v parameter: I want to use the docker volume feature to share the "ip" address of any serverless function to the other functions. 

"it is not guaranteed for actions to run on the same invoker" -- do you mean there could be multiple invokers? And if they are not on the same host, "it's not easy to mount the same directory on each call"

"Even if a container runs with volume mapping, it will be paused after 50ms." -- do you mean the volume mapping will be deferred for 50ms after the container created? Is this by default in docker? Sorry for that I did not quite get this point. 

Yeah, concurrent modification and multi-tenancy isolation should be considered.

**Comment by rabbah** [comment]
>do you mean there could be multiple invokers?

that's correct - functions have transient residency and in a distributed system, the same function may run on multiple nodes (even at the same time).

>  do you mean the volume mapping will be deferred for 50ms after the container created?

no, he means that after the function returns, the container is paused after a grace period (of 50ms but can be changed). This is an openwhisk feature to allow a burst of functions reusing a container to avoid additional container overhead.

Do you have a proposal for an enhancement?
