### ISSUE TITLE
missing active ack from invoker

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#4614]
There are 5 calls to send a "ack" from an invoker (listed below) - 4 of them are completion messages and only 1 is an active ack with the activation result. The calls from `InvokerReactive` only send a completion message and no active acks. This is a bug.

Is there a reason not to send a combined completion/active ack instead of two messages when the result is ready?

https://github.com/apache/openwhisk/blob/b0d48c87816f2e7c04ad9b9f9b4844a6e064047f/core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala#L268

https://github.com/apache/openwhisk/blob/b0d48c87816f2e7c04ad9b9f9b4844a6e064047f/core/invoker/src/main/scala/org/apache/openwhisk/core/invoker/InvokerReactive.scala#L278

https://github.com/apache/openwhisk/blob/b20dffbaf4e8d6ea90da5d8bd233a6b770fa74bb/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala#L289

https://github.com/apache/openwhisk/blob/b20dffbaf4e8d6ea90da5d8bd233a6b770fa74bb/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala#L624

https://github.com/apache/openwhisk/blob/b20dffbaf4e8d6ea90da5d8bd233a6b770fa74bb/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala#L662

**Comment by tysonnorris** [comment]
I believe this was changed a while back to differentiate between "response is available" and "resources are available" so that scheduling at Controller can react accordingly: return response ASAP, reschedule resources only when the container usage (log collection?) is truly complete.

**Comment by rabbah** [comment]
Thanks Tyson. I was slightly confused because there is a completion message that occurs earlier than the active ack but that flow is for the error case.

There are 3 completion messages that have no active ack, which means the controller will have to fetch the activation from a secondary path (couchdb polling for example if enabled) because the activation's promise in the controller is never completed otherwise. 

In those cases, because the activation result is system-constructed, it can be carried as part of the completion message (so that a second message need not be sent).

After further inspection, that's my plan for addressing the issue.

**Comment by sven-lange-last** [comment]
The active ack has been split up into result and completion ack in order to make sequences faster. Before the split, sending the active ack (including the result) was delayed until the action container logs have been processed - in general, until all processing has been completed on the action container that prevents a immediate warm re-use of the container.

The split into result and completion ack server following purposes:
1. the result ack is sent once the activation result is available. When the controller receives the result ack, it can schedule the next action in a sequence or respond to blocking activations.
2. the completion ack is sent once all action container processing has been completed and the container is ready again for warm re-use (or removal). When the controller receives the completion ack, it adjusts the free memory capacity of its shard on the invoker that sent the completion ack.

With the change you proposed / discussed above, you would speed up processing here?

https://github.com/apache/openwhisk/blob/b0d48c87816f2e7c04ad9b9f9b4844a6e064047f/core/controller/src/main/scala/org/apache/openwhisk/core/controller/actions/PrimitiveActions.scala#L581-L594

My conclusion from a quick check is that we omit sending a result ack and only send the completion ack in error situations. Unfortunately, these are not only system errors but application and developer errors as well. Instead of the notion of a "combined result / completion ack", what do you think about a completion ack that indicates an error? A completion ack in error could resolve the result future to unblock waiting...

**Comment by rabbah** [comment]
> Instead of the notion of a "combined result / completion ack", what do you think about a completion ack that indicates an error? A completion ack in error could resolve the result future to unblock waiting...

- For 4 out of the 5 completions, no active ack is sent and hence the controller will wait longer than necessary to resolve the activation's promise.

- To resolve the promise, you need to supply either the activation id or an activation result. Resolving the promise with the former will return an action response such as "request did not finish processing in time" which isn't accurate.

- For all 4 completions in question, the activation result is already present - because it's constructed immediately before sending the completion message. If it is carried in the message that's already sent, it would allow the controller to handle both the completion message and resolve the activation promise. This preserves the intended semantics when the active ack was split into two messages.

- Note that in the absence of the active ack, if the secondary lookup mechanism is enabled, you get the constructed activation from its corresponding store so the bug manifests as a performance bug (waiting 10s of seconds for a result that should have been received sooner).

The split was incomplete and omits active acks for the error cases. We should either send two messages for the 4 out of the 5 cases (Completion and Active Ack), or combine both and send one message as I'm proposing for these cases since there is no additional waiting necessary as in the case where the result is ready but the resource not yet available to be reclaimed.
