### ISSUE TITLE
Add __OW_ACTION_VERSION in action metadata

### ISSUE THREAD

**Issue by cjelger** [apache/openwhisk#4758]
In many cases (e.g. caching), it would be useful that the action code would be able to access the action version in something like `__OW_ACTION_VERSION`. For example, this would allow a developer to create cache keys that would contain the action version and would change after each deployment.

@rabbah On Slack you also mentioned maybe adding some hash to make sure that undeploying and redeploying an action would not recreate similar version numbers, so something like `0.0.1-1a2b3c4d` and `0.0.1-9f8e7d6c`.

I can try to create the PR, never did any Scala but it doesn't look very complicated for that little change ... except I'm not sure about the hash. Any idea here?

**Comment by rabbah** [comment]
We can start without the hash :) please holler if you need a pointer where to look.

For posterity the version is set automatically in the controller so that every update increments the semver but a delete followed by create resets the semver to 0.0.1.

A hash could help but if an action is deleted and recreated identically and the hash is based on a digest of the bits and no other metadata (timestamp?) it could be identical and defeats the versioning being always unique.

There is also the question where to compute the digest/hash as it can consume cycles on a critical path for create/update.

**Comment by cjelger** [comment]
Closed by #4761
