### ISSUE TITLE
Unicode test not running for dotnet:2.2 and dotnet:3.1

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk#4793]
The unicode tests are currently being skipped for the dotnet runtimes.  There appears to be some sources for dotnet 2.2 (openwhisk/tests/dat/actions/unicode.tests/src/dotnet2.2), but the test harness isn't finding them.

```
system.basic.WskUnicodeTests STANDARD_OUT

    test router? false

    Kinds to test: ballerina:0.990, dotnet:2.2, dotnet:3.1, go:1.11, java:8, nodejs:8, nodejs:10, nodejs:12, php:7.3, php:7.4, python:2, python:3, ruby:2.5, swift:4.2

    JUnit version is: 4.12

    WARNING: did not find text or binary action for kind ballerina:0.990, skipping it

    WARNING: did not find text or binary action for kind dotnet:2.2, skipping it

    WARNING: did not find text or binary action for kind dotnet:3.1, skipping it
```

**Comment by rabbah** [comment]
This is actually working as designed. The src needs to be compiled into a binary but we are not including the binaries in this repo. Since compiling these sources also introduces some dependencies that are generally necessary, I dropped building them altogether. Going to close - reopen if you object (meaning we should improve the test harness to run the unicode tests for these languages also).
