### ISSUE TITLE
couchdb is restarting itself very frequently

### ISSUE THREAD

**Issue by ShubhamGupta9582** [apache/openwhisk#4877]
Hi guys,
I'm invoking 18-20 actions in every minute using some cron. After 12-14 hours the openwhisk_db (couchdb) will start restarting itself very frequently and it uses its 100% memory at that time and its cpu will also go to 200% or 300% and its 5984 port (couchdb port) will also become unavailable due to which invoker gives error.
can anyone explain me why it happens? The openwhisk_db container's mem_limit is already 6 GB.

**Comment by style95** [comment]
Please share the logs you found. It would be also great if you share the size of databases in CouchDB.

Did CouchDB crash without any user intervention? or did you run anything such as `wsk activation list`?
It seems CouchDB crashed due to OOM.
I observed a similar symptom when I try to refresh a view results with a high volume of data.
It happens when you've not refreshed your view for a while and some data are piled up in the database and finally, you trigger the view refresh.
Then CouchDB tries to load data and build a view in memory and be crashed eventually.

Since I could observe this situation even with just 10GB data(actually not huge), we are internally using ElasticSearch as an alternative.

**Comment by ShubhamGupta9582** [comment]
![Screenshot from 2020-04-11 16-58-30](https://user-images.githubusercontent.com/30547263/79095891-4a57bc00-7d79-11ea-857f-dd96955520ce.png)
![Screenshot from 2020-04-11 17-10-41](https://user-images.githubusercontent.com/30547263/79095900-52aff700-7d79-11ea-8f87-d40f72fb2eca.png)
![Screenshot from 2020-04-11 17-21-37](https://user-images.githubusercontent.com/30547263/79095913-58a5d800-7d79-11ea-912f-b5a87c27efb7.png)
![Screenshot from 2020-04-11 17-22-13](https://user-images.githubusercontent.com/30547263/79095917-5cd1f580-7d79-11ea-907e-018864e94d4a.png)
![Screenshot from 2020-04-13 11-21-43](https://user-images.githubusercontent.com/30547263/79095925-5fcce600-7d79-11ea-8114-cb151aba6065.png)

**Comment by ShubhamGupta9582** [comment]
First time when i noticed that couchdb restarted itself. I had stopped my cron which was invoking several actions in a minute. and after few minutes i ran cleanUpActivations.py file to clean the activations and after that ow restarted itself very frequently.

![Screenshot from 2020-04-13 11-21-43](https://user-images.githubusercontent.com/30547263/79102437-6020ad80-7d88-11ea-82e2-b215a75ab251.png)
![Screenshot from 2020-04-13 13-09-10](https://user-images.githubusercontent.com/30547263/79102447-62830780-7d88-11ea-9106-5074ddd56258.png)
![Screenshot from 2020-04-13 13-09-36](https://user-images.githubusercontent.com/30547263/79102461-6a42ac00-7d88-11ea-862f-a20a50bc8dfb.png)
![Screenshot from 2020-04-13 13-10-06](https://user-images.githubusercontent.com/30547263/79102476-70d12380-7d88-11ea-9911-6d912d5b5104.png)
![Screenshot from 2020-04-13 13-10-39](https://user-images.githubusercontent.com/30547263/79102488-762e6e00-7d88-11ea-8b86-7825fb975f78.png)

**Comment by style95** [comment]
It seems it is looking for the design docs.
Do all DB have proper design docs?

**Comment by ShubhamGupta9582** [comment]
I didn't make any changes for design docs. So, it should be as it is as it was earlier.

**Comment by ShubhamGupta9582** [comment]
Do i need to change the design docs ? and what does this error means 
**[os_mon] cpu supervisor port (cpu_sup): Erlang has closed** 
**[os_mon] memory supervisor port (memsup): Erlang has closed**

**Comment by ShubhamGupta9582** [comment]
Do i need to change the design docs ? and what do these errors mean
**[os_mon] cpu supervisor port (cpu_sup): Erlang has closed**
**[os_mon] memory supervisor port (memsup): Erlang has closed**

**Comment by style95** [comment]
That means the internal components of CouchDB are closed.
Since CouchDB is running on ErlangVM, I think this is because CouchDB is crashed.

What I can infer from the logs is your view request is timed out.
So it responded with the 500 status code.

![image](https://user-images.githubusercontent.com/3447251/79438281-4c867880-800e-11ea-812a-6903c8da6f96.png)

I think you invoked `wsk activation list` and it triggered the view updates.
Since there are too many documents to update the view, CouchDB might be crashed.

I think what you try is you can periodically trigger view updates before too many documents are piled up. Please see if it happens again with the approach.

**Comment by style95** [comment]
And for the record, If it is because of view updates, this is a CouchDB issue rather than OpenWhisk's one.

**Comment by rabbah** [comment]
This is typically because couch is running on an underpowered VM.
