### ISSUE TITLE
Can't set invocationsPerMinute nor firesPerMinute.

### ISSUE THREAD

**Issue by 842Mono** [apache/openwhisk#5182]
One of invocationsPerMinute or firesPerMinute is limited at 60, and I can't increase it. Not sure why.

First I tried changing the variables in ansible/group_vars/all, but it didn't work.

Then I tried using `wskadmin` (like so: `wskadmin limits set --invocationsPerMinute 999 whisk.system`), but I think I'm not able to set it up correctly, or maybe I'm not using couchdb. I get `Failed to set limits ([Errno 111] Connection refused)`. Here is my `whisk.properties`:

```
WHISK_LOGS_DIR=~/openwhisk/logs
DB_PROTOCOL=http
DB_PORT=5984
DB_HOST=127.0.0.1
DB_USERNAME=whisk_admin
DB_PASSWORD=some_passw0rd
DB_WHISK_AUTHS=local_subjects
DB_WHISK_ACTIONS=local_whisks
DB_WHISK_ACTIVATIONS=local_activations
```

I think I'm just not using the ansible method, and I don't have couchdb. There's no documentation on how to set these variables if I'm not using the ansible method of installation I guess.

To install openwhisk I just install Docker, Java and Node.js, and then run `./gradlew core:standalone:bootRun`. I'm on an Ubuntu 18.04 machine.

**Comment by hawtkey** [comment]
I think this is because couchdb isn't exposed through docker on localhost. wskadmin is trying to access a closed port. I am using a kubernetes/helm deployment but I needed to replace ie: `127.0.0.1` with the IP address of couchdb inside the cluster and exposed as an endpoint by kubernetes. I was able to find this using `kubectl get endpoints -n openwhisk` which produced an output like:
```
NAME               ENDPOINTS                                            AGE
...
owdev-couchdb      10.42.0.184:5984                                     20h
```

so `DB_HOST=10.42.0.184`

then I was able to run wskadmin successfully:

`wskadmin -v user get guest`

```
...
========
REQUEST:
GET http://10.42.0.184:5984/test_subjects/guest
Headers sent:
...
--------
RESPONSE:
Got response with code 200
...
```

The procedure should be similar in docker, IE: `docker container inspect couchdb-container`.

Although I'm still not sure what WHISK_LOGS_DIR should point at, I was able to locate all the other variables by finding them within the helm chart, which should also be similar in docker/ansible- 

See: 
 - https://github.com/apache/openwhisk/blob/master/ansible/README.md#setup
 - https://github.com/apache/openwhisk/blob/master/ansible/templates/db_local.ini.j2
 - https://github.com/apache/openwhisk/blob/af11418df942e8d2cdc4c4ce933645fa723e9e45/ansible/group_vars/all#L250

**Comment by 842Mono** [comment]
So I figured it out.

We can modify this file https://github.com/apache/openwhisk/blob/master/core/standalone/src/main/resources/standalone.conf

It has the lines

```
  config {
    controller-instances = 1
    limits-actions-sequence-maxLength = 50
    limits-triggers-fires-perMinute = 60
    limits-actions-invokes-perMinute = 60
    limits-actions-invokes-concurrent = 30
  }

```
We can modify the limits to what we want.

And then we need to supply the file through the `-c` parameter, through the `--args` parameter. Like so:

    sudo ./gradlew core:standalone:bootRun --args='-c /path/to/openwhisk/core/standalone/src/main/resources/standalone.conf'

That's it.

---

A bit off topic. But there's an alternative way to run openwhisk. We can do

    sudo ./gradlew :core:standalone:build

And this will create a file in the `bin` folder called `openwhisk-standalone.jar`. In general, you can run openwhisk by doing

    sudo java -jar ./bin/openwhisk-standalone.jar

And in our case, we need to supply the `standalone.conf` file through the `-c` parameter to the command above. We can do this:

    sudo java -jar ./bin/openwhisk-standalone.jar -c /path/to/openwhisk/core/standalone/src/main/resources/standalone.conf
