### ISSUE TITLE
The json parameter of the function has a limit of 1M, how to adjust this limit

### ISSUE THREAD

**Issue by crazyzcc619** [apache/openwhisk#5198]
The json parameter of the function has a limit of 1M, how to adjust this limit

**Comment by crazyzcc619** [comment]
Does anyone have any help?

**Comment by style95** [comment]
You can configure that with this option. It's a cluster-wide config.
https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/application.conf#L429

Since it is also related to the maximum bytes the Kafka can receive, you need to increase it as well.
Generally, it is automatically handled by the system when creating the topic.
https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/application.conf#L204

But if you already created the topic, I think you may need to manually alter your Kafka topic configurations accordingly.

**Comment by crazyzcc619** [comment]
thank

















At 2022-03-23 13:06:21, "Dominic Kim" ***@***.***> wrote:

You can configure that with this option. It's a cluster-wide config.
https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/application.conf#L429

Since it is also related to the maximum bytes the Kafka can receive, you need to increase it as well.
Generally, it is automatically handled by the system when creating the topic.
https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/application.conf#L204

But if you already created the topic, I think you may need to manually alter your Kafka topic configurations accordingly.

**Comment by style95** [comment]
closing as answered
