### ISSUE TITLE
How to Replace Docker with Podman

### ISSUE THREAD

**Issue by Yongli0510** [apache/openwhisk#5393]
How to replace Docker with Podman? I want to use Podman to create and run containers in OpenWhisk, because Docker changed its usage license, and Podman is the open-source alternative to Docker. Their commands are almost identical.

**Comment by style95** [comment]
OpenWhisk is using the [DockerContainer](https://github.com/apache/openwhisk/blob/master/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/docker/DockerContainer.scala#L169) or [KubernetesContainer](https://github.com/apache/openwhisk/blob/master/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesContainer.scala#L116) to run containers.


Since it is using [the Container trait](https://github.com/apache/openwhisk/blob/master/common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala#L72), I believe we can add another implementation such as PodmanContainer but for now it does not support it.

**Comment by GeorgeS2019** [comment]
[[WIP] Using Podman for deploying OpenWhisk](https://github.com/apache/openwhisk-runtime-dotnet/issues/81#issuecomment-2403843840)
